### ISSUE TITLE
e2ewd try to query locked cubes

### ISSUE THREAD

**Issue by yeholerner** [kbbgl/e2ewd#1]
`60864679 [2019/03/05 14:56:27.660] [(null)]:[181],[ERROR] [Legacy.Logger]: [Exception Message [ElastiCube 'PM - Revenue' is locked and cannot be queried.]: Type [System.ServiceModel.FaultException`1[ElastiCube.Shared.AbacusDBLockedForProcessingFault]] Exception: [
Server stack trace: 
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at Prism.Web.AppServices.Jaql.QueryService.QueryingDataSource(Query q, String query, UalConnection ualconnection, Action`2 body)
   at Prism.Web.AppServices.Jaql.QueryService.ExecuteReaderInternal(Query q, Action`2 body, String logEntry, QueryTranslationData queryTranslationData)] [<RuntimeInfo assembly="Prism.Runtime.Base" type="Prism.Runtime.Base.RuntimeInfo" DriveTotalSize="0" DriveTotalFreeSpace="0" DriveAvailableFreeSpace="0" AvailableMemory="61092290560" PhysicalMemory="130996092928" AvailableProcessMemory="3150077952" />] [SELECT (o2 .o1  ) AS o1  FROM (SELECT (1) AS o1  FROM (SELECT ("aPMIAAaLQAaIAAaRevenue" .o3  ) AS o3  FROM (SELECT ("aPMIAAaLQAaIAAaRevenue" .o3  ) AS o3  FROM (SELECT ("aPMIAAaLQAaIAAaRevenue" .o3  ) AS o3  FROM (SELECT (1) AS o3 ) "aPMIAAaLQAaIAAaRevenue") "aPMIAAaLQAaIAAaRevenue") "aPMIAAaLQAaIAAaRevenue") o2) o2]]
`

**Comment by kbbgl** [comment]
Issue fixed in version 1.0.8.44817.
