### ISSUE TITLE
When no ECS available on server app crashes with NullPointerException

### ISSUE THREAD

**Issue by kbbgl** [kbbgl/e2ewd#35]
```
C:\Scripts\e2ewd-master\e2ewd-master\build\libs>run
"C:\Program Files\Sisense\Infra\jre\bin\java.exe" -Dlogback.configurationFile="C:\Scripts\e2ewd-master\e2ewd-master\build\libs\logback.xml" -jar "C:\Scripts\e2ewd-master\e2ewd-master\build\libs\e2ewd.jar"
30/08/2019 12:11:02.076 [main] INFO  App - STARTING...
30/08/2019 12:11:02.093 [main] INFO  App - Application version: 2.9.1
30/08/2019 12:11:02.502 [main] INFO  tests.MainTest - Attempt number 1
30/08/2019 12:11:02.512 [main] INFO  tests.MainTest - Retrieving list of ElastiCubes...
30/08/2019 12:11:07.227 [main] INFO  tests.MainTest - No ElastiCubes in RUNNING mode.
Exception in thread "main" java.lang.NullPointerException
        at cmd_ops.CmdOperations.runElastiCube(CmdOperations.java:180)
        at tests.MainTest.run(MainTest.java:96)
        at tests.MainTest.init(MainTest.java:46)
        at App.main(App.java:61)
```

**Comment by kbbgl** [comment]
Same as https://github.com/kbbgl/e2ewd/issues/34
