### ISSUE TITLE
Critical -app doesnt work remotly

### ISSUE THREAD

**Issue by yeholerner** [kbbgl/e2ewd#52]
`        runMicroservicesHealthCheck:false
        requestTimeoutInSeconds:300
        ecDump:false
        }
Found 4 elements
Exception in thread "main" org.json.JSONException: Unterminated string at character 884
        at org.json.JSONTokener.syntaxError(JSONTokener.java:410)
        at org.json.JSONTokener.nextString(JSONTokener.java:244)
        at org.json.JSONTokener.nextValue(JSONTokener.java:341)
        at org.json.JSONObject.<init>(JSONObject.java:205)
        at org.json.JSONTokener.nextValue(JSONTokener.java:344)
        at org.json.JSONObject.<init>(JSONObject.java:205)
        at org.json.JSONObject.<init>(JSONObject.java:402)
        at version.SisenseJSAPIClient.getVersion(SisenseJSAPIClient.java:43)
        at App.main(App.java:51)`

**Comment by kbbgl** [comment]
@yeholerner - Please send me the full log or the server where this happened. This log has insufficient info.

**Comment by yeholerner** [comment]
@kbbgl the issue is with linux servers, seems that the api is different

**Comment by kbbgl** [comment]
@yeholerner - This is known behavior. still need to finish development.
